#? Config file for btop v. 1.4.6

#* Name of a btop++/bpytop/bashtop formatted ".theme" file, "Default" and "TTY" for builtin themes.
#* Themes should be placed in "../share/btop/themes" or "$XDG_CONFIG_HOME/btop/themes"
color_theme = "modus_vivendi"

#* If the theme set background should be shown, set to False if you want terminal background
theme_background = True

#* Sets if rounded corners should be used for boxes
rounded_corners = True
