bass_enable=false
bass_maxgain=0
compander_enable=false
convolver_enable=false
crossfeed_enable=false
ddc_enable=false
graphiceq_enable=false
liveprog_enable=false
master_enable=true
master_limrelease=60
master_limthreshold=0
master_postgain=0
reverb_enable=false
stereowide_enable=false
tone_enable=false
tube_enable=false
