# autogenerated by txs
#include:pict2e
\csname{arg1}#S
\earc#S
\elliparc#S
\ellipse#S
\pIIe#S
\pIIeearc#S
\pIIeelliparc[opt]{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#S
\pIIeelliparc{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#S
\pIIeellipse#S
\\pIIeelliparc#S
\__file_name=pict2e.sty#S
\__file_seen_pict2e.sty:#S
\__hook package/pict2e/after#S
\__hook package/pict2e/before#S
\__hook pict2e#S
\__hook_next package/pict2e/after#S
\__hook_next package/pict2e/before#S
\g__hook_package/pict2e/after_reversed_tl#S
\g__hook_package/pict2e/before_reversed_tl#S
\unprocessedoptions-pict2e.sty#S
csnameendcsname#S
pict2e.sty#S
