# autogenerated by txs
#include:graphicx
\Gfigname#S
\epsfbox#S
\epsfclipoff#S
\epsfclipon#S
\epsffile#S
\epsfig#S
\epsfsize{arg1}{arg2}#S
\epsfverbosefalse#S
\epsfverbosetrue#S
\psdraft#S
\psfigdriver{arg1}#S
\psfig{arg1}#S
\psfull#S
\psnoisy#S
\pssilent#S
\__file_name=graphicx.sty#S
\__file_seen_graphicx.sty:#S
\__hook graphicx#S
\__hook package/graphicx/after#S
\__hook package/graphicx/before#S
\__hook_next package/graphicx/after#S
\__hook_next package/graphicx/before#S
\g__hook_package/graphicx/after_reversed_tl#S
\g__hook_package/graphicx/before_reversed_tl#S
\psfig#S
\unprocessedoptions-graphicx.sty#S
csnameendcsname#S
graphicx.sty#S
