# Preload wallpaper
preload = /usr/share/backgrounds/Resolute_Raccoon_Wallpaper_Dimmed_3840x2160.png

# Set wallpaper for monitor eDP-1
wallpaper = eDP-1,/usr/share/backgrounds/Resolute_Raccoon_Wallpaper_Dimmed_3840x2160.png

# IPC enabled for dynamic changes
ipc = on
