# Preload wallpaper
preload = /usr/share/backgrounds/rubenslp-Twin_brothers.png

# Set wallpaper for monitor eDP-1
wallpaper = eDP-1,/usr/share/backgrounds/rubenslp-Twin_brothers.png

# IPC enabled for dynamic changes
ipc = on
